### ISSUE TITLE
Ruby version does not match Docker Image

### ISSUE THREAD

**Issue by Phhere** [dependabot/dependabot-script#208]
Hello,
i am using the latest master version of dependabot-script with the example gitlab-ci config. It requests the docker container dependabot/dependabot-core which uses ruby 2.5 but the gemfile requires a newer version

https://github.com/dependabot/dependabot-core/blob/master/Dockerfile#L56

Error message in gitlab ci:

`Your Ruby version is 2.5.3, but your Gemfile specified 2.6.1`

**Comment by greysteil** [comment]
Ah, sorry about that. I've reverted that Ruby version update for now. Thanks for flagging, and apologies for not noticing earlier.

**Comment by greysteil** [comment]
@feelepxyz FYI this is my bad for not considering.
