### ISSUE TITLE
`up_to_date?': undefined method `appears_in_lockfile?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ostrolucky** [dependabot/dependabot-script#246]
So I'm trying to debug dependabot issues on one of our projects. @greysteil recommended me to first try to make this script run, but seems it doesn't run. Do you have some pointers to figure out why?

```
ruby update-script.rb
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.2-compliant syntax, but you are running 2.6.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Traceback (most recent call last):
	1: from update-script.rb:91:in `<main>'
/usr/share/rvm/gems/ruby-2.6.1/gems/dependabot-common-0.98.71/lib/dependabot/update_checkers/base.rb:22:in `up_to_date?': undefined method `appears_in_lockfile?' for nil:NilClass (NoMethodError)
```

**Comment by ostrolucky** [comment]
Ok I've successfully used now dry-run script in https://github.com/dependabot/dependabot-core which seems to work, so this is no longer priority for me to solve

**Comment by greysteil** [comment]
Ah, OK. You'd get that error if you had entered a `dependency_name` that wasn't found in the parsing stage (so `dep` was `nil`).
