### ISSUE TITLE
Add Dockerfile + dockerhub integration

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-script#253]
Hi, @greysteil! I am trying to integrate this project to my existing workflow inside Gitlab.
It works great, but still makes me a little bit uncomfortable. 

Because I have to keep `generic-update-script.rb`, `Gemfile`, etc inside my project.
I also have to update gems inside this `Gemfile` as well. 

What do I suggest? 
1. Create `Dockerfile` inside this project with all dependencies
2. Run dockerhub build on each commit
3. Use `image: dependabot/gitlab:latest` inside your own `.gitlab-ci.yml`
4. Use `script: ./generic-update-script.rb` inside your update jobs

Looks like a big improvement to me.
I can help you with `Dockerfile` part and new docs, but I am not able to setup dockerhub integration for you. That's where I need help fro your side.

Cheers!

**Comment by LeoColomb** [comment]
Can a separate repository be considered on your side, @sobolevn? If so, you can follow the small guide on the README: https://github.com/dependabot/dependabot-script#gitlab-ci

**Comment by sobolevn** [comment]
I am not sure about how a separate repository will solve my problem.
I am also not sure why do you suggest this guide. Maybe I am missing something?

**Comment by LeoColomb** [comment]
The easiest configuration (IMO, of course 🙂) is to have a repository dedicated to the script. So your projects are not polluted with dependabot's scripts, and you still have full control on how and when the scripts are used, and we don't need to build an extra docker image.  
Once created, pipeline schedules on that repo can be created to manage every wanted projects. It turns the `[gitlab.domain/org/dependabot-script-repo]/pipeline_schedules` into your own dependabot admin interface.

**Comment by sobolevn** [comment]
Oh, now I see! Thanks for the clarification. That's an awesome approach indeed.

**Comment by LeoColomb** [comment]
Cool! 👍 
Maybe the README need a clarification too. @greysteil Should I?

**Comment by greysteil** [comment]
Thanks for taking this one @LeoColomb! If you reckon you can improve the GitLab CI section of the Readme easily then go for it 🙂
