### ISSUE TITLE
Default assignee

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-script#261]
Is it possible to specify default assignee for all pull-requests?
For example, we have a single person in a team who's responsibility is to review/merge PRs from dependabot.

Or `generic-update-script` should be tweaked manually?

**Comment by sobolevn** [comment]
Is this configuration what I am looking for? https://github.com/dependabot/dependabot-core/blob/master/.dependabot/config.yml

Sorry, but I am not able to find any docs about it 😞

**Comment by greysteil** [comment]
In the script? Yes, you'd just be editing what gets passed to `Dependabot::PullRequestCreator`. The code for that class is [here](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator.rb).

> Is this configuration what I am looking for? https://github.com/dependabot/dependabot-core/blob/master/.dependabot/config.yml

Nope - those are config files for hosted Dependabot, and it sounds like you're using the script, right?

**Comment by sobolevn** [comment]
Ok, that's how to do it:

1. Source code: https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/gitlab.rb#L135
2. Modify these lines:

```ruby
  assignee = ENV['DEPENDABOT_ASSIGNEE_GITLAB_ID']
  pr_creator = Dependabot::PullRequestCreator.new(
    source: source,
    base_commit: commit,
    dependencies: updated_deps,
    files: updated_files,
    credentials: credentials,
    label_language: true,
    assignees: [assignee]
  )
```
