### ISSUE TITLE
Closed merge request is not updated

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-script#264]
For testing reasons I have closed one of the pull requests created by dependabot on Gitlab:
<img width="927" alt="Снимок экрана 2019-04-20 в 16 43 50" src="https://user-images.githubusercontent.com/4660275/56458144-b59bc780-638b-11e9-87d2-78089246733c.png">

And then I executed another pipeline, and I expected that a comment similar to Github's version will be created. Like "Oh, I see that this dependency does not need to be updated, etc"
But, nothing happened. CI log:

```
$ bundle exec ruby ./generic-update-script.rb
Fetching bundler dependency files for wemake.services/kira-dependencies
Parsing dependencies information
  - Updating dependabot-omnibus (from 0.105.6)… submitted
Done
```

Result (none):
<img width="934" alt="Снимок экрана 2019-04-20 в 16 45 53" src="https://user-images.githubusercontent.com/4660275/56458174-001d4400-638c-11e9-9414-3593de520c92.png">

Is it how it should be? Or is there a bug?

**Comment by LeoColomb** [comment]
@sobolevn You need to delete the branch to let dependabot re-push the new version.
This expected. 🙂

**Comment by sobolevn** [comment]
Should I always manually delete branches from closed merge requests? Seems unpractical.

**Comment by sobolevn** [comment]
By the way, it does not update merge request. It creates a new one after deleting a branch: 
<img width="922" alt="Снимок экрана 2019-04-20 в 17 33 13" src="https://user-images.githubusercontent.com/4660275/56458671-758c1300-6392-11e9-8146-9bc47d658b69.png">

**Comment by LeoColomb** [comment]
> By the way, it does not update merge request

It will never. A merge request is linked to a unique git head. If that head is deleted then the merge request will be different. Same behavior on GitHub.


> Seems unpractical.

Well, that how git works... 😉

**Comment by greysteil** [comment]
Yep - Dependabot script is just a script, it's not the full Dependabot app. You won't get all of the goodies the full app has (automatic rebasing, auto-merging, deleting old branches, etc.) - some of those aren't possible on GitLab (rebasing) whilst others would require an app, rather than a script on a cron, to implement.

**Comment by LeoColomb** [comment]
And some available as GitLab own MR features (auto-merging, deleting old branches)!
