### ISSUE TITLE
How-to run the script as a docker container

### ISSUE THREAD

**Issue by whiskeysierra** [dependabot/dependabot-script#284]
I'd like to run the script against repos in our internal GHE, but I have no experience with setting up ruby. Our CI/CD environment is based on Docker images, so the best case scenario would be to have a docker image that contains dependabot core and the script and I can configure it using env vars. Unfortunately due to my lack of ruby skills I can't figure out how to bake this... :cry:

**Comment by LeoColomb** [comment]
@whiskeysierra You can use the official Docker image `dependabot/dependabot-core`.

**Comment by juanjoqmelian** [comment]
I think what he meant was how to set up the dependencies to be able to run the script within that container. I'm in a similar position, I've included the script inside of a container but when I try running it I get the following error:

```
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dependabot/file_fetchers (LoadError)
```

**Comment by LeoColomb** [comment]
You need to install dependencies (`bundle install`) before running. You can run this inside the Docker image.

**Comment by juanjoqmelian** [comment]
Hi @LeoColomb, where in the container? The root path doesn't seem to contain any Gemfile to be able to install the dependencies.

**Comment by LeoColomb** [comment]
In the working directory, where a volume refers to this repository's files (`dependabot-script`).

**Comment by juanjoqmelian** [comment]
Thanks @LeoColomb. What's the expected format in PROJECT_PATH env variable? I keep getting `raise_invalid_repository` error.

**Comment by juanjoqmelian** [comment]
Nevermind, it's working now `organisation/projectName` worked. The problem I'm having now is that the `GitMetadataFetcher` is configured to only accept some known hosts:

https://github.com/dependabot/dependabot-core/blob/61cba023cc91bbba66d7d55b50d080fac603f342/common/lib/dependabot/git_metadata_fetcher.rb#L8

Raising an exception if it doesn't match:

https://github.com/dependabot/dependabot-core/blob/61cba023cc91bbba66d7d55b50d080fac603f342/common/lib/dependabot/git_metadata_fetcher.rb#L57

Our Github Enterprise url doesn't match with those, is there any reason for that?

**Comment by LeoColomb** [comment]
> Nevermind, it's working now organisation/projectName worked

Cool. Every of these variables are documented in the script file. 

> The problem I'm having now 

This is a totally different issue, I suggest you open a new ticket on the feedback repository.

**Comment by LeoColomb** [comment]
@dependabot I think this issue can be closed. That said, three or four lines may be added to the readme to explain the basic usage with the docker image.

**Comment by greysteil** [comment]
👍 and would love a PR with Docker usage instructions.

**Comment by juanjoqmelian** [comment]
> 👍 and would love a PR with Docker usage instructions.

I would if I could, but it's still not working inside the container. I was running it on my local.

I've mounted dependabot-script as a volume into the container, ran bundle install, dependencies are installed in `/home/dependabot/.bundle` but somehow when I run the script it still can't find file_fetchers.

For example:

```
/home/dependabot/dependabot-script# bundle show dependabot-dep --paths
/home/dependabot/.bundle/gems/dependabot-dep-0.112.6
```

**Comment by juanjoqmelian** [comment]
Fixed it now, will create a PR when I'm free.

I had to add these variables to let the script find the dependencies in the right place:

```
export GEM_HOME="/usr/local/bundle"
export PATH=$GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH
```

**Comment by juanjoqmelian** [comment]
@LeoColomb @greysteil I have a change ready to include the docs on how to use the Docker image to run the script, but it seems that I have no permissions to push to a branch in this repo.

**Comment by greysteil** [comment]
Fab! If you fork the repo and push to your fork you’ll be able to create a PR here. Looking forward to the contribution!

**Comment by juanjoqmelian** [comment]
Done! Thanks @greysteil
