### ISSUE TITLE
Providing ECR credentials

### ISSUE THREAD

**Issue by thiemok** [dependabot/dependabot-script#293]
From issues in depedabot-core I read that aws ecr hosted docker dependencies are supported. However I'm not sure how to provide credentials for ecr if used with dependabot-script.
Is this even possible? Can you provide documentation on this?

**Comment by greysteil** [comment]
For sure. You can provide creds for ECR in the script the same way you would if you were adding them in the Dependabot dashboard - here are to docs we show there:

![image](https://user-images.githubusercontent.com/1144873/58708004-6e531e80-83ae-11e9-8c4e-4e02f8e37f7a.png)

Thanks for using Dependabot! 🙂

**Comment by thiemok** [comment]
Thats great, however I'm not sure where to add the variables in the script.

**Comment by greysteil** [comment]
Oh, of course, sorry! Just add an additional element to [this array](https://github.com/dependabot/dependabot-script/blob/master/update-script.rb#L18-L23) that looks like:

```
{"type"=>"docker_registry", "registry"=>"111111etc.dkr.ecr.region.amazonaws.com", "username"=>"AKIAetcetc", "password"=>"secret"}
```

**Comment by thiemok** [comment]
ah, perfect! Thanks a lot.
