### ISSUE TITLE
rebase a MR

### ISSUE THREAD

**Issue by gperdomor** [dependabot/dependabot-script#306]
Hi... I have a question...

How can I force a merge request rebase on gitlab?

**Comment by greysteil** [comment]
Sadly the GitLab API doesn't support it (or at least it didn't last time I checked), so Dependabot doesn't have a `PullRequestUpdater` class for GitLab.

**Comment by gperdomor** [comment]
@greysteil what about this? https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request

**Comment by greysteil** [comment]
That won't work if there are conflicts - what Dependabot needs is a way to force push a commit (via the API).

**Comment by fmasa** [comment]
@greysteil I think that using `force` option on [/commits](https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions) should do the trick. 
![image](https://user-images.githubusercontent.com/5658260/63476559-9ddf6780-c481-11e9-8064-2983a897d22e.png)

**Comment by greysteil** [comment]
That looks good - I'd be happy to accept a PR to Dependabot Core to  add `PullRequestUpdater`  logic  for GitLab.

**Comment by gperdomor** [comment]
@greysteil any updates on this? I think this should be reopened

**Comment by greysteil** [comment]
The next step would be for someone to author a `PullRequestUpdater` class in Dependabot Core for GitLab. That could then be incorporated here (although this script would also need to be updated with the ability to update PRs - currently it just creates them).

**Comment by mente** [comment]
@greysteil https://github.com/dependabot/dependabot-core/pull/1808 was merged . I've tried latest PR https://github.com/dependabot/dependabot-script/pull/446 and it still results in no rebases, neither merge conflicts resolution.

Any hints where to move on?

**Comment by MoonLiightz** [comment]
Same here. Are there any changes to the update-script necessary?

**Comment by mente** [comment]
Given my very limited Ruby knowledge and looking at both PR from the core and the script in this repo I gues there shouldn't be any changes. But then it also means it should have worked :D

**Comment by stefangr** [comment]
With my almost non-existing Ruby knowledge, I see that a new class is added to update a pull request (in the core).

However, that class needs to be implemented in the script before it will actually update a pull request (as @greysteil already mentioned).

And a bit of glue code is also missing.
The update class requires a `pull_request_number` that cannot be fetched with the current core code.

**Comment by mente** [comment]
My knowledge is also non-existing, otherwise I would have taken a look. Maybe @ahivert can take a peek here?

**Comment by ahivert** [comment]
@mente @MoonLiightz  Like I said in my PR to the core (https://github.com/dependabot/dependabot-core/pull/1808#issuecomment-627133638), I have a branch that do what you want.

(just to clarify things, after using the script from this project, I decided to use the script from https://github.com/wemake-services/kira-dependencies because support looks better.)
 
You can take inspiration from the last commit of the branch "update-a-merge-request" (https://github.com/ahivert/kira-dependencies/tree/update-a-merge-request)

I will open a PR to kira-dependencies project to enable merge request update.

**Comment by ahivert** [comment]
PR is now opened on kira-dependencies -> https://github.com/wemake-services/kira-dependencies/pull/171

**Comment by mente** [comment]
Great, thanks! Will take a look there and try out kira-dependencies. I liked this one so far as it was mostly plug'n'play experience
