### ISSUE TITLE
Conventional Commits

### ISSUE THREAD

**Issue by asummers** [dependabot/dependabot-script#313]
Dependabot core seems to be able to understand when a repo is using conventional commits, but it seems that Dependabot Script does not honor that. Is there some flag I can give it to force it to do so?

**Comment by greysteil** [comment]
Yes - if you add the following as an argument to the `PullRequestCreator` you can control the prefix used:

```
...
credentials: credentials,
commit_message_options: {
  prefix: "chore",
  include_scope: true,
}
```

More generally, Dependabot Core contains the logic to automatically detect the right commit prefix to use, but adding the above to it will allow you to specify it manually.
