### ISSUE TITLE
Add an example Azure DevOps pipeline yml file

### ISSUE THREAD

**Issue by NateRadebaugh** [dependabot/dependabot-script#318]
There is already an example for GitLab CI, but there is not one for Azure DevOps. The script and core do seem to support Azure, but there is no documentation or examples on how to actually set it up.

It would be good to document Azure DevOps usage.

**Comment by greysteil** [comment]
Happy to accept a PR from anyone on this one! :octocat:

**Comment by wavemotionio** [comment]
We had trouble, presumably because ado forces ruby @2.6.3. The workaround was to add a docker-compose.yml to a fork of this repo and use a series of release pipeline stages to run the docker steps outlined in the README.

**Comment by MO2k4** [comment]
Maybe this blog entry is helping out

=> https://medium.com/@acraven/updating-dependencies-in-azure-devops-repos-773cbbb6029d
=> https://github.com/acraven/azure-dependabot

**Comment by jeffwidman** [comment]
I just merged #676 which provides a working example per https://github.com/dependabot/dependabot-script/pull/676#issuecomment-1135400520.
