### ISSUE TITLE
Add support for updating subdependencies

### ISSUE THREAD

**Issue by m-aciek** [dependabot/dependabot-script#358]
:wave: Currently only direct/top-level dependencies are kept up to date by this script. It would be great if it would be possible to enable also updating subdependencies of a project.

Related ticket on dependabot/feedback: https://github.com/dependabot/feedback/issues/669.

**Comment by greysteil** [comment]
This is really just an example script. If you want to change it to also update sub-dependencies that should be a pretty easy change on your side (just remove the filtering on `top_level?`).
