### ISSUE TITLE
Ruby version mismatch

### ISSUE THREAD

**Issue by b1rdex** [dependabot/dependabot-script#376]
```
Running with gitlab-runner 12.3.0 (a8a019e0)
  on gitlab702.zzz.ru iNrxm2Lv
Using Docker executor with image dependabot/dependabot-core ...
Pulling docker image dependabot/dependabot-core ...
Using docker image sha256:a0c6498168b3333203010d869fb24d885344422a8e80ae71a55bf694aa6d26e9 for dependabot/dependabot-core ...
Running on runner-iNrxm2Lv-project-23-concurrent-0 via 2852ec717367...
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/zzz/dependabot/.git/
From https://gitlab.zzz.ru/zzz/dependabot
   b7784a7..96ea85f  master     -> origin/master
Checking out 96ea85f1 as master...
Removing .bundle/
Removing vendor/

Skipping Git submodules setup
Checking cache for default...
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted. 
Successfully extracted cache
$ bundle install -j $(nproc) --path vendor
Your Ruby version is 2.6.5, but your Gemfile specified 2.6.2
ERROR: Job failed: exit code 1
```

**Comment by greysteil** [comment]
This just needs you to update the Ruby version the script is using (would accept a PR updating to 2.6.5) or install the older Ruby version on you GitLab runner.

**Comment by b1rdex** [comment]
Well, I use https://github.com/dependabot/dependabot-script/blob/master/.gitlab-ci.example.yml and it uses `dependabot/dependabot-core` docker image that has wrong Ruby bundled in it. Could you please update Gemfile? Or lock ruby version in dependabot/dependabot-core.

**Comment by b1rdex** [comment]
I'm really surprised you closed the issue… Please see #263 where you got it right :)

**Comment by b1rdex** [comment]
Also, even internal CI failed with the same error… See https://github.com/dependabot/dependabot-script/pull/377/checks?check_run_id=267763782

**Comment by greysteil** [comment]
My bad - updated.

**Comment by b1rdex** [comment]
Thank you very much :) sorry if I was not polite. 

Отправлено с iPhone
