### ISSUE TITLE
SSL certificate verify failed error while access self hosted Gitlab repo

### ISSUE THREAD

**Issue by pravin-raha** [dependabot/dependabot-script#414]
I am trying to setup dependabot on premise server for private gitlab repo. But it is throwing  this error 

`Faraday::Error::ClientError.inherited called from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.

/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /usr/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/httparty-0.17.1/lib/httparty/request.rb:145:in `perform'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/httparty-0.17.1/lib/httparty.rb:594:in `perform_request'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/httparty-0.17.1/lib/httparty.rb:508:in `get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/gitlab-4.12.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/gitlab-4.12.0/lib/gitlab/client/projects.rb:49:in `project'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/gitlab_with_retries.rb:67:in `public_send'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/gitlab_with_retries.rb:67:in `block in method_missing'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/gitlab_with_retries.rb:82:in `retry_connection_failures'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/gitlab_with_retries.rb:64:in `method_missing'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/gitlab_with_retries.rb:51:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:395:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:61:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:310:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:320:in `_fetch_file_content'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:90:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-maven-0.113.28/lib/dependabot/maven/file_fetcher.rb:32:in `pom'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-maven-0.113.28/lib/dependabot/maven/file_fetcher.rb:25:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/file_fetchers/base.rb:55:in `files'
	from ./generic-update-script.rb:115:in `<main>'
`

Is there any way I can add ssl certificate to octokit client( I don't know ruby) .
I am using docker.

**Comment by pravin-raha** [comment]
I have just figure it out. I have to added my ssl certificate to linux ca-store.

**Comment by pravin-raha** [comment]
To use docker. need to create new image from dependabot-core with certficate

`FROM dependabot/dependabot-core:latest

COPY <your_certificate>.crt /usr/share/ca-certificates/

RUN echo <your_certificate>.crt  >> /etc/ca-certificates.conf

RUN apt-get update && apt-get install -y ca-certificates

RUN apt install curl -y

RUN update-ca-certificates `

**Comment by elg0ch0** [comment]
How did you provide the credentials to dependabot (standalone mode) to pull your custom-created image?

I updated .gitlab-ci.yml file with:
```
.dependabot:
  image:
    name: my_registry/dependabot/custom.dependabot:3.13.3-alpha.1 

```
but when I try to run the pipeline:
```
ERROR: Job failed: failed to pull image "my_registry/dependabot/custom.dependabot:3.13.3-alpha.1" with specified policies [always]: Error response from daemon: pull access denied for my_registry/dependabot/custom.dependabot:3.13.3-alpha.1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied (manager.go:250:0s)

```

even if 
```
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - bundle exec rake "dependabot:update[$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME,$PACKAGE_MANAGER,/]"

```

**Comment by elg0ch0** [comment]
Never mind... my runner was missing the credentials in its .toml file
