### ISSUE TITLE
GitHub Api limit exceeded - TooManyRequests

### ISSUE THREAD

**Issue by DhruvM1994** [dependabot/dependabot-script#417]
I am trying to use the script for a GitLab repository. Thereby, a GitLab Access Token is specified.
The above setting leads to following output:
```
/builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/fabric8io/fabric8-maven-plugin/contents/doc: 403 - API rate limit exceeded for <ip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting (Octokit::TooManyRequests)
``` 
I thought that dependabot fetches the dependency information (in case of maven) from maven central. So why does it hit GitHub API limit?

**Comment by bgrainger** [comment]
The script is updating a dependency that's hosted on GitHub, and is using the GitHub API to get its version history, release notes, etc.

You should supply both a GitLab API token and a GitHub API token to the script.

**Comment by augi** [comment]
I can confirm that setting also `GITHUB_ACCESS_TOKEN` (alongside with `GITHUB_ENTERPRISE_ACCESS_TOKEN` etc.) eliminated the `403 - API rate limit exceeded` errors.

**Comment by sscholl** [comment]
I can confirm @augi 's problem. Same here.

**Comment by jeffwidman** [comment]
Thanks @bgrainger and @augi for helping out with the solution here.

**Comment by sscholl** [comment]
@jeffwidman  what is the solution? I dont unterstand.
