### ISSUE TITLE
Add Bitbucket support

### ISSUE THREAD

**Issue by iinuwa** [dependabot/dependabot-script#512]
I think this should be pretty simple once dependabot/dependabot-core#2917 and dependabot/dependabot-core#2919 are resolved.

**Comment by JaredAAT** [comment]
@iinuwa please see: https://github.com/dependabot/dependabot-script/issues/588 but after my changes are accepted, i think this issue can be closed.

**Comment by iinuwa** [comment]
I left a note for you in that issue and PR. I'll close this one since the main functionality has been merged in #580.
