### ISSUE TITLE
Best way to setup a bot?

### ISSUE THREAD

**Issue by manuelpuyol** [dependabot/dependabot-script#55]
I'd like to host my own bot on Oracle Cloud and I don't know which is the best way to set it up.

Is there a way to create a service that runs continuously and check dependencies every day, or should I setup my script like the one provided and run it every day (like an AWS Lambda)?

**Comment by greysteil** [comment]
My advice would be to set it up using the loop in the GitLab update script (here)[https://github.com/dependabot/dependabot-script/blob/master/gitlab-update-script.rb#L75-L78], and set it to run every day. The process to actually do updates can be quite slow depending on the language you're updating (for PHP we have to actually pull down the dependencies, for example. For other languages we can avoid that so things are fast).

If you want to do something a bit more challenging you could make your service listen for webhooks from the repository you're using, but that might be quite a lot more work.

**Comment by greysteil** [comment]
(Doing a daily check is the way that Dependabot itself ran for the first 6 months of its life - it's only more recently that we've started offering live updates. Daily checks were totally sufficient for pretty much everyone's needs!)
