### ISSUE TITLE
Specify package manager version

### ISSUE THREAD

**Issue by zimmicz** [dependabot/dependabot-script#553]
I'm using dependabot-script with gitlab repo that's strictly set to use npm 6. Dependabot runs npm 7 and that results in the following error:

```
Parsing dependencies information
  - Updating @lingui/core (from 2.9.2)…/opt/gitlab-runner/frontend/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.133.6/lib/dependabot/shared_helpers.rb:284:in `run_shell_command': npm WARN using --force Recommended protections disabled. (Dependabot::SharedHelpers::HelperSubprocessFailed)
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: livesport-tv@0.0.1
npm ERR! notsup Not compatible with your version of node/npm: livesport-tv@0.0.1
npm ERR! notsup Required: {"node":">= 12","npm":"^6"}
npm ERR! notsup Actual:   {"npm":"7.6.1","node":"v14.16.0"}
```

I have a good reason to stick to version 6. Is there a way to tell dependabot to respect the version as well?

**Comment by feelepxyz** [comment]
@zimmicz hm we attempt to ignore the engine checks, could you put together a sample/anonymized repo that reproduces the error?

If you have a `package-lock.json` checked in dependabot selects the npm version based on the `lockfileVersion`.

**Comment by zimmicz** [comment]
@feelepxyz thanks for a prompt response! It seems we were in the middle of a huge dependency update combined with updating npm from v6 to v7. Along the way, I guess we committed package.json with 
```
  "engines": {
    "node": ">= 12",
    "npm": "^6"
  },
```
and package-lock.json with
```
  "lockfileVersion": 2,
```
at the same time.

Is that something that could be hard to deal with for dependabot?

**Comment by feelepxyz** [comment]
> ```
>   "lockfileVersion": 2,
> ```

You'll want to change this to `"lockfileVersion": 1` for npm 6. If you regenerate the lockfile with `npm install` locally and make sure npm 6 is installed there it should set this for you.

**Comment by zimmicz** [comment]
I found out we fixed that along the way, and dependabot is working just fine with the proper combination of those two constraints. I'd close this ticket, because the trouble was rather caused by misusing the npm than dependabot itself. Do you agree?
