### ISSUE TITLE
Add support for BitBucket App Passwords

### ISSUE THREAD

**Issue by JaredAAT** [dependabot/dependabot-script#588]
Following on from the work that's been done to add BitBucket support, BitBucket App Password support should be added to allow BitBucket cloud users to run the script on their pipelines.

BitBucket Access Tokens are only for users of BitBucket server and not BitBucket Cloud.

**Comment by JaredAAT** [comment]
Added here: https://github.com/dependabot/dependabot-script/pull/589

I think Dependabot also needs changes to accept the user/pass as credentials.

**Comment by JaredAAT** [comment]
Dependabot-core doesn't need any changes.  

I did note that the changes for BitBucket server don't make use of branch (it's set as nil https://github.com/dependabot/dependabot-script/blob/main/generic-update-script.rb#L116) which i think would break it's usage.  Do you want me to fix in my branch?

**Comment by iinuwa** [comment]
Adding app password support is a welcome change!

> BitBucket Access Tokens are only for users of BitBucket server and not BitBucket Cloud.

I only tested on Bitbucket Cloud, so I don't think is true; could you elaborate?

**Comment by JaredAAT** [comment]
> Adding app password support is a welcome change!
> 
> > BitBucket Access Tokens are only for users of BitBucket server and not BitBucket Cloud.
> 
> I only tested on Bitbucket Cloud, so I don't think is true; could you elaborate?

When i was looking at how to generate a Token for BitBucket, it seemed to suggest that this was only available to users of BitBucket Server: https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html

Maybe i misunderstood or was looking at the wrong thing? Either way I came to the conclusion that App Password support would be required.

**Comment by iinuwa** [comment]
Ah, I see. Yeah, the Bitbucket Server documentation is completely unaware of the Bitbucket Cloud documentation in some places, so you have to go to the specific docs in order to get the right information.

**Comment by JaredAAT** [comment]
Gonna bump this up... @feelepxyz any chance you could get eyes on it (sorry for calling you out, would be good to get this merged in though)
