### ISSUE TITLE
Running Dependabot script on private hosted Gitlab

### ISSUE THREAD

**Issue by mohameddhouibi** [dependabot/dependabot-script#663]
Hi 
i have an issue that looks very strange to me (as i am new in this stuff) . the used dependabot script is not respecting gemfile locked version (for example i have : gem "rails", "~> 6.0.3.6" the dependabot update it to 6.1.4 )
is there an obvious solution for this ? 
thanks a lot

**Comment by jeffwidman** [comment]
The whole point of Dependabot is to open PR's bumping dependencies.
