### ISSUE TITLE
Providing BITBUCKET_ACCESS_TOKEN alone couldn't get dependabot-core to clone my private Bitbucket repository

### ISSUE THREAD

**Issue by central182** [dependabot/dependabot-script#664]
### Problem
Bitbucket requires the following syntax to clone a (possibly private) repository with an access token, according to the _Repository Cloning_ section of https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication.
```
git clone https://x-token-auth:{access_token}@bitbucket.org/user/repo.git
```

When calling `generic-update-script.rb` with a BITBUCKET_ACCESS_TOKEN, `username` and `password` are empty and therefore not passed to the `configure_git_to_use_https_with_credentials` method of dependabot-core, which however assumes the two fields to be present. (See https://github.com/dependabot/dependabot-core/blob/v0.156.4/common/lib/dependabot/shared_helpers.rb#L212-L214)

This resulted in the following error messages when I tried to run
```bash
docker run --rm \
  --env "PROJECT_PATH=___/___" \
  --env "PACKAGE_MANAGER=go_modules" \
  --env "BITBUCKET_ACCESS_TOKEN=___" \
  --env "GITHUB_ACCESS_TOKEN=___" \
  "dependabot/dependabot-script"
```

```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Fetching go_modules dependency files for ___/___
/home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:84:in `rescue in clone_repo_contents': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:80:in `clone_repo_contents'
	from /home/dependabot/.bundle/gems/dependabot-go_modules-0.142.0/lib/dependabot/go_modules/file_fetcher.rb:24:in `fetch_files'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./generic-update-script.rb:154:in `<main>'
/home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:294:in `run_shell_command': Cloning into 'tmp/___/___'... (Dependabot::SharedHelpers::HelperSubprocessFailed)
fatal: could not read Username for 'https://bitbucket.org': No such device or address
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:480:in `block in _clone_repo_contents'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:159:in `with_git_configured'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:472:in `_clone_repo_contents'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:82:in `clone_repo_contents'
	from /home/dependabot/.bundle/gems/dependabot-go_modules-0.142.0/lib/dependabot/go_modules/file_fetcher.rb:24:in `fetch_files'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./generic-update-script.rb:154:in `<main>'
```

### Temporary Workaround
I was able to get around the issue by the following modification of `generic-update-script.rb`. (It was necessary, though, to follow https://github.com/dependabot/dependabot-core/pull/3197 as well to get dependabot work fully with Bitbucket repositories.)
```diff
diff --git a/generic-update-script.rb b/generic-update-script.rb
index 29f2b65..b1686a2 100644
--- a/generic-update-script.rb
+++ b/generic-update-script.rb
@@ -103,7 +103,8 @@ elsif ENV["BITBUCKET_ACCESS_TOKEN"]
   credentials << {
     "type" => "git_source",
     "host" => bitbucket_hostname,
-    "username" => nil,
+    "username" => "x-token-auth",
+    "password" => ENV["BITBUCKET_ACCESS_TOKEN"],
     "token" => ENV["BITBUCKET_ACCESS_TOKEN"]
   }
```

**Comment by rimas-kudelis** [comment]
@central182 care to reveal how you generated the access token?
I've been busy taming Dependabot this afternoon, but I couldn't find a way to generate a token for an app in Bitbucket repository settings.

**Comment by central182** [comment]
Hi @rimas-kudelis, you can have a look on https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/.

Later (after I created this issue) I figured out that I can generate an [app password](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/) and use it on behalf of my account. This should take less effort than generating an OAuth token.
```
git clone https://{username}:{app_password}@bitbucket.org/{username}/{repo}.git
```

**Comment by rimas-kudelis** [comment]
Yeah, I found the app password management panel already. A token seems somewhat more appropriate though, assuming it can be disassociated from my own account and seen as a bot that it is.

But thanks anyway!

**Comment by jeffwidman** [comment]
Looks like https://github.com/dependabot/dependabot-script/pull/736/files#diff-6b47430943f20b3a1a6dd41cd62be1602657b8becf8bb99c66693c85678e671dR106 would fix this. Just need the PR re-opened per https://github.com/dependabot/dependabot-script/pull/736#pullrequestreview-1108550739.
