### ISSUE TITLE
Dependabot error with Bitbucket server Clients::Bitbucket::NotFound

### ISSUE THREAD

**Issue by rsaiprashanth** [dependabot/dependabot-script#693]
I have tried dependabot-script with Azure devops and had no big hurdles (I noticed Dependabot throws error repo not found when the I used user access token rather than system access token in ADO using private artifact feeds), but now trying with enterprise Bitbucket server I only see this error.

Could you please guide me here?

docker run --rm -v "$(pwd):/home/dependabot/dependabot-script" -w /home/dependabot/dependabot-script -e BITBUCKET_ACCESS_TOKEN=$BITBUCKET_ACCESS_TOKEN -e GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -e PACKAGE_MANAGER=npm_and_yarn -e PROJECT_PATH=projects/project_name/repos/repo_name bundle exec ruby ./generic-update-script.rb

Error /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.142.0/lib/dependabot/clients/bitbucket.rb:170:in `Clients::Bitbucket::NotFound)

**Comment by viswanathan-mani** [comment]
Me too have the same issue. Will there be any fix for the error?

**Comment by aperkaz** [comment]
I am having the same issue, any updates?

**Comment by jeffwidman** [comment]
I think this is a dupe of #664 since you're trying to auth via an access token but the script was passing the wrong username. That was fixed in #859
