### ISSUE TITLE
Dependabot in Azure DevOps - rate limits

### ISSUE THREAD

**Issue by ahmed-babic** [dependabot/dependabot-script#718]
Hi, we are trying to run dependabot in Azure DevOps (using dependabot-script), but we are forced to use github token in order to not hit the threshold limits.

Is there any way to run dependabot without this github token for auth? What kind of apis requests are sent to github? Before enrolling we also need to verify the type of data that is sent from our Azure DevOps instance to Github in these requests?

Is it going to work if I take the same repo, move it to AzDO and sync via pipeline that all github changes are replicated to AzDO? What kind of obstacles I could get while doing it?
We just want to avoid this github token.
Thank you for your answer :)

**Comment by jeffwidman** [comment]
This repo is just a collection of example scripts to use as a starting point for those who wish to run dependabot themselves.

I'm afraid your questions are about how to use these scripts for your specific use case, and unfortunately we don't have the resources to provide support.

For AzDO, I just merged a PR from another contributor who got it working: https://github.com/dependabot/dependabot-script/pull/676. Maybe you'll find that helpful?
