### ISSUE TITLE
Bitbucket dependabot/dependabot-script doesn't work

### ISSUE THREAD

**Issue by It-Soul** [dependabot/dependabot-script#723]
Hello.
I try to run dependabot/dependabot-script for Bitbucket and have all time some errors.
I use to run in docker like this: 
`docker run -ti --rm "$(pwd):/mnt/d/dependabot-script" -w /mnt/d/dependabot-script -e BITBUCKET_APP_USERNAME=${USER} -e BITBUCKET_APP_PASSWORD=${PASSWORD} -e PACKAGE_MANAGER=gradle -e PROJECT_PATH=${PROJECT/REPO} "dependabot/dependabot-script"`
after the run I receive an error:
`warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.3-compliant syntax, but you are running 2.7.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/mnt/d/Elevate/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.142.0/lib/dependabot/pull_request_creator/labeler.rb:241:in `labels': Unsupported provider bitbucket (RuntimeError)`
I try to build docker image file from the master branch, also try to update the version in Dockerfile from 0.142.0 to 0.169.8 [Dockerfile](https://github.com/dependabot/dependabot-script/blob/main/Dockerfile)
I am doing everything via documentation.
Please help with instructions on how to run dependabot on bitbucket with BITBUCKET_APP_USERNAME and BITBUCKET_APP_PASSWORD
I wasted 3 days and had no luck to make run.

**Comment by rimas-kudelis** [comment]
@It-Soul, this has nothing to do with Bitbucket specifically, it's due to a bumped version of Ruby (somewhere), but an oudated Gemfiles.lock.

I had this exact issue today as well and made a PR which fixes it by updating both the base docker image and all Gem dependencies: #734.

**Comment by dependb** [comment]
**I updated the files as per @rimas-kudelis . And then ran the following script below.**

`
cryo_ch33m@IE4LLT93J0YD3:~/dependabot-script$ docker run -ti -e BITBUCKET_APP_USERNAME=${USERNAME} -e BITBUCKET_APP_PASSWORD=${PASSWORD} -e PROJECT_PATH=${PROJECT_PATH} -e DIRECTORY_PATH=${DIRECTORY_PATH} -e PACKAGE_MANAGER=pip  "dependabot/dependabot-script"
`

**But I got this error in dependency.**
`
Activating bundler (~> 2.3) failed:
Could not find 'bundler' (2.3.13) required by your /home/dependabot/dependabot-script/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.3.13`
Checked in 'GEM_PATH=/home/dependabot/.local/share/gem/ruby/2.7.0:/usr/lib/ruby/gems/2.7.0' , execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '~> 2.3'`

`

**Comment by jeffwidman** [comment]
Closing as I _think_ this was fixed by https://github.com/dependabot/dependabot-script/pull/740.
