### ISSUE TITLE
Error after run

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-script#86]
Hi!

So, with the (incorrect, unreviewed) changes in the PRs I just opened, I run the script. It sucessfully created 17 PRs, and then it failed with:

```
Traceback (most recent call last):
	7: from bin/dependabot:10:in `<main>'
	6: from bin/dependabot:10:in `load'
	5: from /home/deivid/Code/nipanipa/bin/dependabot-script/gitlab-update-script.rb:74:in `<top (required)>'
	4: from /home/deivid/Code/nipanipa/bin/dependabot-script/gitlab-update-script.rb:74:in `each'
	3: from /home/deivid/Code/nipanipa/bin/dependabot-script/gitlab-update-script.rb:97:in `block in <top (required)>'
	2: from /home/deivid/Code/nipanipa/.bundle/ruby/2.5.0/bundler/gems/dependabot-core-211620be1cc9/lib/dependabot/file_updaters/ruby/bundler.rb:30:in `updated_dependency_files'
	1: from /home/deivid/Code/nipanipa/.bundle/ruby/2.5.0/bundler/gems/dependabot-core-211620be1cc9/lib/dependabot/file_updaters/ruby/bundler.rb:101:in `updated_lockfile_content'
/home/deivid/Code/nipanipa/.bundle/ruby/2.5.0/bundler/gems/dependabot-core-211620be1cc9/lib/dependabot/file_updaters/ruby/bundler/lockfile_updater.rb:48:in `updated_lockfile_content': Expected content to change! (RuntimeError)
```

Not sure if it's due to the problems you detected in the PRs, with the way I'm running the script, or with a real bug somewhere? :man_shrugging:

Reporting just in case it's helpful.

**Comment by greysteil** [comment]
That looks like it must be a bug in the script (or Dependabot Core, but that's less likely, as I'd almost certainly have seen it and fixed it already on someone else's repo).

Let me take a quick look.

**Comment by deivid-rodriguez** [comment]
Don't waste too much time here, maybe it was due to the problems you detected in my PRs. If I run into it again I'll let you know.

**Comment by greysteil** [comment]
Nah, it'll be that this script is super basic and doesn't cover some edge cases. I've just updated it - shouldn't error like that again.

**Comment by deivid-rodriguez** [comment]
Thanks!
